/**
 * Enterprise Computer & Hardware Specification Presets
 * Ported & adapted from ComNet Enterprise Accounting standard taxonomy
 */

export const SPECIFICATION_FIELDS = [
  "Brand",
  "Model",
  "Part Number",
  "Condition",
  "Product Category",
  "Processor Brand",
  "Processor Model",
  "Processor Generation",
  "Processor Cores",
  "Socket Type",
  "RAM Capacity",
  "RAM Type",
  "Storage Capacity",
  "Storage Type",
  "Graphics Card",
  "Graphics Memory",
  "Form Factor",
  "Power Supply Wattage",
  "Screen Size",
  "Resolution",
  "Display Technology",
  "Touchscreen",
  "Color",
  "Operating System",
  "Keyboard Language",
  "Keyboard Type",
  "Backlit Keyboard",
  "Fingerprint Reader",
  "Stylus / Pen Support",
  "Included Bag / Case",
  "Power Source & Battery",
  "Computer Form Factor",
  "Computer Intended Use",
  "Disclosures",
  // Enterprise Storage & HDD fields
  "HDD RPM",
  "HDD Cache",
  "HDD Interface Protocol",
  "HDD Intended Workload",
  "HDD Series",
  "HDD Form Factor",
  "Warranty",
  "Country of Origin",
  "Notes",
] as const;

export type SpecificationField = (typeof SPECIFICATION_FIELDS)[number];

export const SPECIFICATION_PRESETS: Record<string, string[]> = {
  Brand: [
    "ASUS",
    "Acer",
    "AMD",
    "Apple",
    "Corsair",
    "Dell",
    "EVGA",
    "Gigabyte",
    "HP",
    "HP Enterprise",
    "Intel",
    "Kingston",
    "Lenovo",
    "Microsoft",
    "MSI",
    "NVIDIA",
    "Samsung",
    "Seagate",
    "Western Digital",
    "Toshiba",
  ],
  Condition: [
    "Brand New (Factory Sealed)",
    "Open Box",
    "Refurbished",
    "Enterprise Recertified",
    "Used (Tested & Cleaned)",
  ],
  "Product Category": [
    "Processors (CPUs)",
    "Graphics Cards (GPUs)",
    "Enterprise Rackmount Servers",
    "Motherboards",
    "Memory (RAM)",
    "Storage (NVMe/SSD/HDD)",
    "Power Supplies (PSUs)",
    "Laptops & Workstations",
    "All-in-One Desktops",
    "Enterprise Networking",
    "Monitors & Displays",
  ],
  "Processor Brand": ["Intel", "AMD", "Apple Silicon", "Qualcomm Snapdragon"],
  "Processor Generation": [
    "12th Gen Alder Lake",
    "13th Gen Raptor Lake",
    "14th Gen Raptor Lake Refresh",
    "Core Ultra Series 1 (Meteor Lake)",
    "Core Ultra Series 2 (Arrow Lake)",
    "AMD Ryzen 7000 Series",
    "AMD Ryzen 8000 Series",
    "AMD Ryzen 9000 Series",
    "AMD EPYC 9004/9005 Series",
    "Intel Xeon Scalable (Emerald Rapids)",
  ],
  "Processor Cores": [
    "Quad-Core (4 Cores)",
    "Hexa-Core (6 Cores)",
    "Octa-Core (8 Cores)",
    "Deca-Core (10 Cores)",
    "Dodeca-Core (12 Cores)",
    "14 Cores",
    "16 Cores",
    "24 Cores",
    "32 Cores",
    "64 Cores",
    "96 Cores",
    "128 Cores",
  ],
  "Socket Type": ["LGA1700", "LGA1851", "AM4", "AM5", "LGA4677", "SP5"],
  "RAM Capacity": [
    "8GB",
    "16GB",
    "24GB",
    "32GB",
    "48GB",
    "64GB",
    "96GB",
    "128GB",
    "256GB",
  ],
  "RAM Type": [
    "DDR4 3200MHz",
    "DDR4 3600MHz",
    "DDR5 5600MHz",
    "DDR5 6000MHz",
    "DDR5 6400MHz",
    "LPDDR5X",
    "DDR5 ECC Registered",
  ],
  "Storage Capacity": [
    "256GB",
    "512GB",
    "1TB",
    "2TB",
    "4TB",
    "8TB",
    "15.36TB (Enterprise)",
  ],
  "Storage Type": [
    "NVMe PCIe 4.0 SSD",
    "NVMe PCIe 5.0 SSD",
    'SATA III 2.5" SSD',
    "Enterprise SAS 12G HDD",
    "Enterprise U.2 / U.3 NVMe",
  ],
  "Graphics Memory": [
    "Integrated",
    "Integrated / Shared",
    "6GB GDDR6",
    "8GB GDDR6",
    "12GB GDDR6X",
    "16GB GDDR6X",
    "24GB GDDR6X",
    "48GB GDDR6 (Enterprise)",
  ],
  "Form Factor": [
    "ATX",
    "Micro-ATX",
    "Mini-ITX",
    "E-ATX",
    "1U Rackmount",
    "2U Rackmount",
    "4U Rackmount",
  ],
  "Display Technology": [
    "LED Backlit",
    "IPS Anti-Glare",
    "OLED (True Black)",
    "Mini-LED",
    "Retina Display",
    "TN Panel",
  ],
  Touchscreen: ["No", "Yes (Multi-Touch)", "Yes (Stylus Active Pen)"],
  Color: [
    "Silver",
    "Space Gray",
    "Black",
    "Dark Ash Silver",
    "Platinum",
    "Midnight Blue",
    "White",
  ],
  "Backlit Keyboard": ["Yes", "No", "RGB Per-Key Backlit"],
  "Keyboard Type": [
    "Island-style Chiclet",
    "Full-size with Numpad",
    "Compact Tenkeyless",
    "Mechanical Switches",
    "Low-profile",
  ],
  "Fingerprint Reader": ["Yes", "No"],
  "Stylus / Pen Support": [
    "No",
    "Yes (Included)",
    "Yes (Supported, Sold Separately)",
  ],
  "Included Bag / Case": [
    "No",
    "Yes (Executive Laptop Bag)",
    "Yes (Protective Sleeve)",
  ],
  "Power Source & Battery": [
    "Rechargeable 3-Cell 45Wh",
    "Rechargeable 3-Cell 56Wh",
    "Rechargeable 4-Cell 70Wh",
    "Rechargeable 6-Cell 90Wh",
    "AC Power Supply 65W USB-C",
    "AC Power Supply 100W USB-C",
    "AC Power Supply 230W Smart Barrel",
  ],
  "Computer Form Factor": [
    "Notebook / Clamshell",
    "2-in-1 Convertible (360°)",
    "Ultraportable / Thin & Light",
    "Mobile Workstation",
    "Ruggedized Field Laptop",
  ],
  "Computer Intended Use": [
    "Home & Business",
    "Enterprise Corporate Fleet",
    "Pro Creator & CAD",
    "High-Performance Gaming",
    "Engineering & Data Science",
  ],
  "Keyboard Language": [
    "English (US)",
    "English / Arabic (Bilingual GCC)",
    "English / Russian",
    "English / French",
  ],
  "Operating System": [
    "No OS / FreeDOS",
    "DOS",
    "Windows 11 Pro",
    "Windows 11 Home",
    "Windows Server 2022",
    "Red Hat Enterprise Linux",
    "Ubuntu Server LTS",
  ],
  // Enterprise Storage / HDD presets
  "HDD RPM": ["5400 RPM", "7200 RPM", "10000 RPM", "15000 RPM"],
  "HDD Cache": ["64MB Cache", "128MB Cache", "256MB Cache", "512MB Cache"],
  "HDD Interface Protocol": [
    "SATA III 6Gb/s",
    "SAS 12Gb/s",
    "PCIe Gen4 U.2 / U.3",
    "Fibre Channel (FC)",
  ],
  "HDD Intended Workload": [
    "Enterprise 24/7 Datacenter",
    "NAS (Network Attached Storage)",
    "Surveillance / CCTV Continuous Recording",
    "Desktop / Workstation Client",
  ],
  "HDD Series": [
    "Seagate IronWolf Pro",
    "Seagate Exos Enterprise",
    "Western Digital Red Pro",
    "Western Digital Gold Enterprise",
    "Western Digital Ultrastar",
    "Toshiba MG Series Enterprise",
  ],
  "HDD Form Factor": [
    '3.5" Large Form Factor (LFF)',
    '2.5" Small Form Factor (SFF)',
    "M.2 2280 NVMe",
    'U.2 2.5" NVMe',
  ],
  Warranty: [
    "3 Years Official Manufacturer Warranty",
    "2 Years Regional GCC Warranty",
    "1 Year Official Warranty",
    "One Year Shop Warranty",
    "3 Months Reseller Replacement Warranty",
    "Lifetime Limited Warranty (RAM/SSD)",
  ],
};
