/**
 * Enterprise Computer & Hardware Specification Presets
 * Ported & adapted from ComNet Enterprise Accounting standard taxonomy
 */

export const SPECIFICATION_FIELDS = [
  'Brand',
  'Model',
  'Part Number',
  'Condition',
  'Product Category',
  'Processor Brand',
  'Processor Model',
  'Processor Generation',
  'Socket Type',
  'RAM Capacity',
  'RAM Type',
  'Storage Capacity',
  'Storage Type',
  'Graphics Card',
  'Graphics Memory',
  'Form Factor',
  'Power Supply Wattage',
  'Screen Size',
  'Resolution',
  'Keyboard Language',
  'Operating System',
  'Warranty',
  'Country of Origin',
  'Notes',
] as const;

export type SpecificationField = typeof SPECIFICATION_FIELDS[number];

export const SPECIFICATION_PRESETS: Record<string, string[]> = {
  Brand: [
    'ASUS',
    'Acer',
    'AMD',
    'Apple',
    'Corsair',
    'Dell',
    'EVGA',
    'Gigabyte',
    'HP Enterprise',
    'Intel',
    'Kingston',
    'Lenovo',
    'Microsoft',
    'MSI',
    'NVIDIA',
    'Samsung',
    'Seagate',
    'Western Digital',
  ],
  Condition: [
    'Brand New (Factory Sealed)',
    'Open Box',
    'Refurbished',
    'Enterprise Recertified',
    'Used (Tested & Cleaned)',
  ],
  'Product Category': [
    'Processors (CPUs)',
    'Graphics Cards (GPUs)',
    'Enterprise Rackmount Servers',
    'Motherboards',
    'Memory (RAM)',
    'Storage (NVMe/SSD/HDD)',
    'Power Supplies (PSUs)',
    'Laptops & Workstations',
    'All-in-One Desktops',
    'Enterprise Networking',
    'Monitors & Displays',
  ],
  'Processor Brand': ['Intel', 'AMD', 'Apple Silicon', 'Qualcomm Snapdragon'],
  'Processor Generation': [
    '12th Gen Alder Lake',
    '13th Gen Raptor Lake',
    '14th Gen Raptor Lake Refresh',
    'Core Ultra Series 1 (Meteor Lake)',
    'Core Ultra Series 2 (Arrow Lake)',
    'AMD Ryzen 7000 Series',
    'AMD Ryzen 8000 Series',
    'AMD Ryzen 9000 Series',
    'AMD EPYC 9004/9005 Series',
    'Intel Xeon Scalable (Emerald Rapids)',
  ],
  'Socket Type': [
    'LGA1700',
    'LGA1851',
    'AM4',
    'AM5',
    'LGA4677',
    'SP5',
  ],
  'RAM Capacity': ['8GB', '16GB', '24GB', '32GB', '48GB', '64GB', '96GB', '128GB', '256GB'],
  'RAM Type': ['DDR4 3200MHz', 'DDR4 3600MHz', 'DDR5 5600MHz', 'DDR5 6000MHz', 'DDR5 6400MHz', 'LPDDR5X', 'DDR5 ECC Registered'],
  'Storage Capacity': ['256GB', '512GB', '1TB', '2TB', '4TB', '8TB', '15.36TB (Enterprise)'],
  'Storage Type': ['NVMe PCIe 4.0 SSD', 'NVMe PCIe 5.0 SSD', 'SATA III 2.5" SSD', 'Enterprise SAS 12G HDD', 'Enterprise U.2 / U.3 NVMe'],
  'Graphics Memory': ['Integrated', '6GB GDDR6', '8GB GDDR6', '12GB GDDR6X', '16GB GDDR6X', '24GB GDDR6X', '48GB GDDR6 (Enterprise)'],
  'Form Factor': ['ATX', 'Micro-ATX', 'Mini-ITX', 'E-ATX', '1U Rackmount', '2U Rackmount', '4U Rackmount'],
  'Keyboard Language': [
    'English (US)',
    'English / Arabic (Bilingual GCC)',
    'English / Russian',
    'English / French',
  ],
  'Operating System': [
    'No OS / FreeDOS',
    'Windows 11 Home',
    'Windows 11 Pro',
    'Windows Server 2022',
    'Red Hat Enterprise Linux',
    'Ubuntu Server LTS',
  ],
  Warranty: [
    '3 Years Official Manufacturer Warranty',
    '2 Years Regional GCC Warranty',
    '1 Year Official Warranty',
    '3 Months Reseller Replacement Warranty',
    'Lifetime Limited Warranty (RAM/SSD)',
  ],
};
