import { Category, Brand } from '@/types';

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'cat_processors',
    name: 'Processors (CPUs)',
    slug: 'processors',
    description: 'High-performance desktop, workstation, and server CPUs from Intel and AMD',
    icon: 'Cpu',
    order: 1,
    isActive: true,
    productCount: 8,
  },
  {
    id: 'cat_gpus',
    name: 'Graphics Cards (GPUs)',
    slug: 'gpus',
    description: 'Discrete desktop and AI workstation accelerators from NVIDIA and AMD',
    icon: 'Zap',
    order: 2,
    isActive: true,
    productCount: 6,
  },
  {
    id: 'cat_motherboards',
    name: 'Motherboards',
    slug: 'motherboards',
    description: 'Enthusiast and workstation motherboards across LGA1700, LGA1851, and AM5',
    icon: 'Cpu',
    order: 3,
    isActive: true,
    productCount: 5,
  },
  {
    id: 'cat_ram',
    name: 'Memory (RAM)',
    slug: 'ram',
    description: 'High-speed DDR5, DDR4, and ECC Registered server memory kits',
    icon: 'Database',
    order: 4,
    isActive: true,
    productCount: 6,
  },
  {
    id: 'cat_storage',
    name: 'Storage (NVMe/SSD/HDD)',
    slug: 'storage',
    description: 'High-speed PCIe Gen5 NVMe SSDs, Enterprise SAS drives, and U.2/U.3 drives',
    icon: 'HardDrive',
    order: 5,
    isActive: true,
    productCount: 7,
  },
  {
    id: 'cat_psus',
    name: 'Power Supplies (PSUs)',
    slug: 'power-supplies',
    description: 'ATX 3.0, PCIe 5.0 80 Plus Gold, Platinum, and Titanium power supplies',
    icon: 'Zap',
    order: 6,
    isActive: true,
    productCount: 4,
  },
  {
    id: 'cat_servers',
    name: 'Enterprise Rackmount Servers',
    slug: 'servers',
    description: '1U/2U/4U Rack servers, Dual Xeon/EPYC compute nodes, and SAN/NAS storage',
    icon: 'Server',
    order: 7,
    isActive: true,
    productCount: 5,
  },
  {
    id: 'cat_laptops',
    name: 'Laptops & Workstations',
    slug: 'laptops',
    description: 'Mobile workstations, ultrabooks, and high-performance gaming laptops',
    icon: 'Laptop',
    order: 8,
    isActive: true,
    productCount: 6,
  },
  {
    id: 'cat_desktops',
    name: 'All-in-One Desktops',
    slug: 'desktops',
    description: 'Pre-built precision workstations and all-in-one desktop computing systems',
    icon: 'Monitor',
    order: 9,
    isActive: true,
    productCount: 4,
  },
  {
    id: 'cat_networking',
    name: 'Enterprise Networking',
    slug: 'networking',
    description: '10GbE/100GbE managed switches, enterprise routers, and firewalls',
    icon: 'Network',
    order: 10,
    isActive: true,
    productCount: 5,
  },
  {
    id: 'cat_monitors',
    name: 'Monitors & Displays',
    slug: 'monitors',
    description: 'Color-calibrated 4K UHD, 5K2K, OLED, and ultrawide enterprise displays',
    icon: 'Monitor',
    order: 11,
    isActive: true,
    productCount: 4,
  },
  {
    id: 'cat_components',
    name: 'PC Components & Hardware',
    slug: 'components',
    description: 'Comprehensive computer components, cooling, cases, and expansion kits',
    icon: 'Cpu',
    order: 12,
    isActive: true,
    productCount: 12,
  },
  {
    id: 'cat_accessories',
    name: 'Accessories & Peripherals',
    slug: 'accessories',
    description: 'Mechanical keyboards, precision mice, docks, and enterprise accessories',
    icon: 'Keyboard',
    order: 13,
    isActive: true,
    productCount: 6,
  },
];

export const DEFAULT_BRANDS: Brand[] = [
  {
    id: 'brand_intel',
    name: 'Intel',
    slug: 'intel',
    logo: '/brands/intel.svg',
    tier: 'TIER_1',
    description: 'Xeon Scalable & Core Ultra Direct',
    website: 'https://www.intel.com',
    isActive: true,
    productCount: 6,
  },
  {
    id: 'brand_nvidia',
    name: 'NVIDIA',
    slug: 'nvidia',
    logo: '/brands/nvidia.svg',
    tier: 'TIER_1',
    description: 'Ada Lovelace & Hopper AI Accelerators',
    website: 'https://www.nvidia.com',
    isActive: true,
    productCount: 5,
  },
  {
    id: 'brand_amd',
    name: 'AMD',
    slug: 'amd',
    logo: '/brands/amd.svg',
    tier: 'TIER_1',
    description: 'EPYC Server & Ryzen Threadripper Direct',
    website: 'https://www.amd.com',
    isActive: true,
    productCount: 6,
  },
  {
    id: 'brand_asus',
    name: 'ASUS',
    slug: 'asus',
    logo: '/brands/asus.svg',
    tier: 'TIER_1',
    description: 'ROG & ProArt Workstation Components',
    website: 'https://www.asus.com',
    isActive: true,
    productCount: 8,
  },
  {
    id: 'brand_dell',
    name: 'Dell Technologies',
    slug: 'dell',
    logo: '/brands/dell.svg',
    tier: 'TIER_1',
    description: 'PowerEdge Server Infrastructure & Systems',
    website: 'https://www.dell.com',
    isActive: true,
    productCount: 5,
  },
  {
    id: 'brand_hpe',
    name: 'HP Enterprise',
    slug: 'hp-enterprise',
    logo: '/brands/hpe.svg',
    tier: 'TIER_1',
    description: 'ProLiant & Apollo High-Density Compute',
    website: 'https://www.hpe.com',
    isActive: true,
    productCount: 4,
  },
  {
    id: 'brand_lenovo',
    name: 'Lenovo',
    slug: 'lenovo',
    logo: '/brands/lenovo.svg',
    tier: 'TIER_1',
    description: 'ThinkSystem Enterprise & Precision Workstations',
    website: 'https://www.lenovo.com',
    isActive: true,
    productCount: 4,
  },
  {
    id: 'brand_cisco',
    name: 'Cisco Systems',
    slug: 'cisco',
    logo: '/brands/cisco.svg',
    tier: 'TIER_1',
    description: 'Catalyst & Nexus Enterprise Switching',
    website: 'https://www.cisco.com',
    isActive: true,
    productCount: 4,
  },
  {
    id: 'brand_supermicro',
    name: 'Supermicro',
    slug: 'supermicro',
    logo: '/brands/supermicro.svg',
    tier: 'TIER_1',
    description: 'AI SuperServer Systems & GPU Blades',
    website: 'https://www.supermicro.com',
    isActive: true,
    productCount: 4,
  },
  {
    id: 'brand_samsung',
    name: 'Samsung Semiconductor',
    slug: 'samsung',
    logo: '/brands/samsung.svg',
    tier: 'TIER_1',
    description: 'Enterprise NVMe Gen5 Data Center SSDs',
    website: 'https://semiconductor.samsung.com',
    isActive: true,
    productCount: 5,
  },
  {
    id: 'brand_kingston',
    name: 'Kingston Technology',
    slug: 'kingston',
    logo: '/brands/kingston.svg',
    tier: 'TIER_1',
    description: 'Server Premier DDR5 ECC Registered Memory',
    website: 'https://www.kingston.com',
    isActive: true,
    productCount: 4,
  },
  {
    id: 'brand_corsair',
    name: 'Corsair',
    slug: 'corsair',
    logo: '/brands/corsair.svg',
    tier: 'TIER_1',
    description: 'Dominator DDR5 & High-Performance Enclosures',
    website: 'https://www.corsair.com',
    isActive: true,
    productCount: 5,
  },
  {
    id: 'brand_seasonic',
    name: 'Seasonic Power',
    slug: 'seasonic',
    logo: '/brands/seasonic.svg',
    tier: 'TIER_1',
    description: 'PRIME Titanium High-Efficiency PSU Architect',
    website: 'https://seasonic.com',
    isActive: true,
    productCount: 4,
  },
  {
    id: 'brand_wd',
    name: 'Western Digital',
    slug: 'western-digital',
    logo: '/brands/wd.svg',
    tier: 'TIER_1',
    description: 'Ultrastar High-Capacity Data Center Drives',
    website: 'https://www.westerndigital.com',
    isActive: true,
    productCount: 4,
  },
  {
    id: 'brand_seagate',
    name: 'Seagate Technology',
    slug: 'seagate',
    logo: '/brands/seagate.svg',
    tier: 'TIER_1',
    description: 'Exos Enterprise & IronWolf Pro High-Reliability Storage',
    website: 'https://www.seagate.com',
    isActive: true,
    productCount: 4,
  },
  {
    id: 'brand_gigabyte',
    name: 'Gigabyte',
    slug: 'gigabyte',
    logo: '/brands/gigabyte.svg',
    tier: 'TIER_1',
    description: 'AORUS & HPC Server Motherboards',
    website: 'https://www.gigabyte.com',
    isActive: true,
    productCount: 4,
  },
  {
    id: 'brand_msi',
    name: 'MSI',
    slug: 'msi',
    logo: '/brands/msi.svg',
    tier: 'TIER_1',
    description: 'MEG & Creator High-End Hardware',
    website: 'https://www.msi.com',
    isActive: true,
    productCount: 4,
  },
  {
    id: 'brand_synology',
    name: 'Synology',
    slug: 'synology',
    logo: '/brands/synology.svg',
    tier: 'TIER_1',
    description: 'Enterprise NAS & SAN Storage Arrays',
    website: 'https://www.synology.com',
    isActive: true,
    productCount: 3,
  },
  {
    id: 'brand_fortinet',
    name: 'Fortinet',
    slug: 'fortinet',
    logo: '/brands/fortinet.svg',
    tier: 'TIER_1',
    description: 'FortiGate Enterprise Network Security',
    website: 'https://www.fortinet.com',
    isActive: true,
    productCount: 3,
  },
  {
    id: 'brand_crucial',
    name: 'Crucial by Micron',
    slug: 'crucial',
    logo: '/brands/crucial.svg',
    tier: 'TIER_1',
    description: 'Pro Overclocking & Server DRAM Solutions',
    website: 'https://www.crucial.com',
    isActive: true,
    productCount: 3,
  },
];
