import { Category, Brand } from '@/types';

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'cat_components',
    name: 'PC Components',
    slug: 'components',
    description: 'CPUs, GPUs, Motherboards, RAM, and Power Supplies',
    icon: 'Cpu',
    order: 1,
    isActive: true,
    productCount: 10,
  },
  {
    id: 'cat_laptops',
    name: 'Laptops',
    slug: 'laptops',
    description: 'Ultrabooks, gaming laptops, and mobile workstations',
    icon: 'Laptop',
    order: 2,
    isActive: true,
    productCount: 4,
  },
  {
    id: 'cat_desktops',
    name: 'Desktop Computers',
    slug: 'desktops',
    description: 'Pre-built gaming rigs and enterprise workstations',
    icon: 'Monitor',
    order: 3,
    isActive: true,
    productCount: 3,
  },
  {
    id: 'cat_servers',
    name: 'Servers & Enterprise',
    slug: 'servers',
    description: 'Rack servers, Xeon/EPYC hardware, and NAS storage',
    icon: 'Server',
    order: 4,
    isActive: true,
    productCount: 3,
  },
  {
    id: 'cat_networking',
    name: 'Networking Devices',
    slug: 'networking',
    description: 'Routers, managed switches, access points, and firewalls',
    icon: 'Network',
    order: 5,
    isActive: true,
    productCount: 3,
  },
  {
    id: 'cat_storage',
    name: 'Storage & Drives',
    slug: 'storage',
    description: 'High-speed PCIe Gen5 NVMe SSDs, Enterprise HDDs',
    icon: 'HardDrive',
    order: 6,
    isActive: true,
    productCount: 3,
  },
  {
    id: 'cat_accessories',
    name: 'Accessories & Peripherals',
    slug: 'accessories',
    description: 'Mechanical keyboards, 4K monitors, and headsets',
    icon: 'Keyboard',
    order: 7,
    isActive: true,
    productCount: 4,
  },
];

export const DEFAULT_BRANDS: Brand[] = [
  {
    id: 'brand_asus',
    name: 'ASUS',
    slug: 'asus',
    logo: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 6,
  },
  {
    id: 'brand_intel',
    name: 'Intel',
    slug: 'intel',
    logo: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 4,
  },
  {
    id: 'brand_amd',
    name: 'AMD',
    slug: 'amd',
    logo: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 4,
  },
  {
    id: 'brand_nvidia',
    name: 'NVIDIA',
    slug: 'nvidia',
    logo: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 3,
  },
  {
    id: 'brand_dell',
    name: 'Dell Technologies',
    slug: 'dell',
    logo: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 4,
  },
  {
    id: 'brand_corsair',
    name: 'Corsair',
    slug: 'corsair',
    logo: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 4,
  },
  {
    id: 'brand_samsung',
    name: 'Samsung Semiconductor',
    slug: 'samsung',
    logo: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 3,
  },
  {
    id: 'brand_cisco',
    name: 'Cisco Systems',
    slug: 'cisco',
    logo: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 3,
  },
  {
    id: 'brand_lenovo',
    name: 'Lenovo',
    slug: 'lenovo',
    logo: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 3,
  },
  {
    id: 'brand_msi',
    name: 'MSI',
    slug: 'msi',
    logo: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 3,
  },
  {
    id: 'brand_gigabyte',
    name: 'Gigabyte',
    slug: 'gigabyte',
    logo: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 3,
  },
];
