import { Category, Brand } from '@/types';

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'cat_processors',
    name: 'Processors (CPUs)',
    slug: 'processors',
    description: 'High-performance desktop, workstation, and server CPUs from Intel and AMD',
    icon: 'Cpu',
    order: 1,
    isActive: true,
    productCount: 8,
  },
  {
    id: 'cat_gpus',
    name: 'Graphics Cards (GPUs)',
    slug: 'gpus',
    description: 'Discrete desktop and AI workstation accelerators from NVIDIA and AMD',
    icon: 'Zap',
    order: 2,
    isActive: true,
    productCount: 6,
  },
  {
    id: 'cat_motherboards',
    name: 'Motherboards',
    slug: 'motherboards',
    description: 'Enthusiast and workstation motherboards across LGA1700, LGA1851, and AM5',
    icon: 'Cpu',
    order: 3,
    isActive: true,
    productCount: 5,
  },
  {
    id: 'cat_ram',
    name: 'Memory (RAM)',
    slug: 'ram',
    description: 'High-speed DDR5, DDR4, and ECC Registered server memory kits',
    icon: 'Database',
    order: 4,
    isActive: true,
    productCount: 6,
  },
  {
    id: 'cat_storage',
    name: 'Storage (NVMe/SSD/HDD)',
    slug: 'storage',
    description: 'High-speed PCIe Gen5 NVMe SSDs, Enterprise SAS drives, and U.2/U.3 drives',
    icon: 'HardDrive',
    order: 5,
    isActive: true,
    productCount: 7,
  },
  {
    id: 'cat_psus',
    name: 'Power Supplies (PSUs)',
    slug: 'power-supplies',
    description: 'ATX 3.0, PCIe 5.0 80 Plus Gold, Platinum, and Titanium power supplies',
    icon: 'Zap',
    order: 6,
    isActive: true,
    productCount: 4,
  },
  {
    id: 'cat_servers',
    name: 'Enterprise Rackmount Servers',
    slug: 'servers',
    description: '1U/2U/4U Rack servers, Dual Xeon/EPYC compute nodes, and SAN/NAS storage',
    icon: 'Server',
    order: 7,
    isActive: true,
    productCount: 5,
  },
  {
    id: 'cat_laptops',
    name: 'Laptops & Workstations',
    slug: 'laptops',
    description: 'Mobile workstations, ultrabooks, and high-performance gaming laptops',
    icon: 'Laptop',
    order: 8,
    isActive: true,
    productCount: 6,
  },
  {
    id: 'cat_desktops',
    name: 'All-in-One Desktops',
    slug: 'desktops',
    description: 'Pre-built precision workstations and all-in-one desktop computing systems',
    icon: 'Monitor',
    order: 9,
    isActive: true,
    productCount: 4,
  },
  {
    id: 'cat_networking',
    name: 'Enterprise Networking',
    slug: 'networking',
    description: '10GbE/100GbE managed switches, enterprise routers, and firewalls',
    icon: 'Network',
    order: 10,
    isActive: true,
    productCount: 5,
  },
  {
    id: 'cat_monitors',
    name: 'Monitors & Displays',
    slug: 'monitors',
    description: 'Color-calibrated 4K UHD, 5K2K, OLED, and ultrawide enterprise displays',
    icon: 'Monitor',
    order: 11,
    isActive: true,
    productCount: 4,
  },
  {
    id: 'cat_components',
    name: 'PC Components & Hardware',
    slug: 'components',
    description: 'Comprehensive computer components, cooling, cases, and expansion kits',
    icon: 'Cpu',
    order: 12,
    isActive: true,
    productCount: 12,
  },
  {
    id: 'cat_accessories',
    name: 'Accessories & Peripherals',
    slug: 'accessories',
    description: 'Mechanical keyboards, precision mice, docks, and enterprise accessories',
    icon: 'Keyboard',
    order: 13,
    isActive: true,
    productCount: 6,
  },
];

export const DEFAULT_BRANDS: Brand[] = [
  {
    id: 'brand_asus',
    name: 'ASUS',
    slug: 'asus',
    logo: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 8,
  },
  {
    id: 'brand_intel',
    name: 'Intel',
    slug: 'intel',
    logo: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 6,
  },
  {
    id: 'brand_amd',
    name: 'AMD',
    slug: 'amd',
    logo: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 6,
  },
  {
    id: 'brand_nvidia',
    name: 'NVIDIA',
    slug: 'nvidia',
    logo: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 5,
  },
  {
    id: 'brand_dell',
    name: 'Dell',
    slug: 'dell',
    logo: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 5,
  },
  {
    id: 'brand_corsair',
    name: 'Corsair',
    slug: 'corsair',
    logo: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 5,
  },
  {
    id: 'brand_samsung',
    name: 'Samsung',
    slug: 'samsung',
    logo: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 5,
  },
  {
    id: 'brand_cisco',
    name: 'Cisco Systems',
    slug: 'cisco',
    logo: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 4,
  },
  {
    id: 'brand_lenovo',
    name: 'Lenovo',
    slug: 'lenovo',
    logo: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 4,
  },
  {
    id: 'brand_msi',
    name: 'MSI',
    slug: 'msi',
    logo: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 4,
  },
  {
    id: 'brand_gigabyte',
    name: 'Gigabyte',
    slug: 'gigabyte',
    logo: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 4,
  },
  {
    id: 'brand_acer',
    name: 'Acer',
    slug: 'acer',
    logo: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 3,
  },
  {
    id: 'brand_apple',
    name: 'Apple',
    slug: 'apple',
    logo: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 4,
  },
  {
    id: 'brand_evga',
    name: 'EVGA',
    slug: 'evga',
    logo: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 3,
  },
  {
    id: 'brand_hp',
    name: 'HP Enterprise',
    slug: 'hp-enterprise',
    logo: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 4,
  },
  {
    id: 'brand_kingston',
    name: 'Kingston',
    slug: 'kingston',
    logo: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 4,
  },
  {
    id: 'brand_microsoft',
    name: 'Microsoft',
    slug: 'microsoft',
    logo: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 3,
  },
  {
    id: 'brand_seagate',
    name: 'Seagate',
    slug: 'seagate',
    logo: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 4,
  },
  {
    id: 'brand_wd',
    name: 'Western Digital',
    slug: 'western-digital',
    logo: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    productCount: 4,
  },
];
