/**
 * Enterprise Computer & Hardware Specification Presets
 * Synchronized with backend/src/constants/specifications.ts
 */

export const SPECIFICATION_FIELDS = [
  'Brand',
  'Model',
  'Part Number',
  'Condition',
  'Product Category',
  'Processor Brand',
  'Processor Model',
  'Processor Generation',
  'Processor Cores',
  'Socket Type',
  'RAM Capacity',
  'RAM Type',
  'Storage Capacity',
  'Storage Type',
  'Graphics Card',
  'Graphics Memory',
  'Form Factor',
  'Power Supply Wattage',
  'Screen Size',
  'Resolution',
  'Display Technology',
  'Touchscreen',
  'Color',
  'Operating System',
  'Keyboard Language',
  'Keyboard Type',
  'Backlit Keyboard',
  'Fingerprint Reader',
  'Stylus / Pen Support',
  'Included Bag / Case',
  'Power Source & Battery',
  'Computer Form Factor',
  'Computer Intended Use',
  'Disclosures',
  // Enterprise Storage & HDD fields
  'HDD RPM',
  'HDD Cache',
  'HDD Interface Protocol',
  'HDD Intended Workload',
  'HDD Series',
  'HDD Form Factor',
  'Warranty',
  'Country of Origin',
  'Notes',
] as const;

export type SpecificationField = typeof SPECIFICATION_FIELDS[number];

export const SPECIFICATION_PRESETS: Record<string, string[]> = {
  Brand: [
    'ASUS',
    'Acer',
    'AMD',
    'Apple',
    'Corsair',
    'Dell',
    'EVGA',
    'Gigabyte',
    'HP',
    'HP Enterprise',
    'Intel',
    'Kingston',
    'Lenovo',
    'Microsoft',
    'MSI',
    'NVIDIA',
    'Samsung',
    'Seagate',
    'Western Digital',
    'Toshiba',
  ],
  Condition: [
    'Brand New (Factory Sealed)',
    'Open Box',
    'Refurbished',
    'Enterprise Recertified',
    'Used (Tested & Cleaned)',
  ],
  'Product Category': [
    'Processors (CPUs)',
    'Graphics Cards (GPUs)',
    'Enterprise Rackmount Servers',
    'Motherboards',
    'Memory (RAM)',
    'Storage (NVMe/SSD/HDD)',
    'Power Supplies (PSUs)',
    'Laptops & Workstations',
    'All-in-One Desktops',
    'Enterprise Networking',
    'Monitors & Displays',
  ],
  'Processor Brand': ['Intel', 'AMD', 'Apple Silicon', 'Qualcomm Snapdragon'],
  'Processor Generation': [
    '12th Gen Alder Lake',
    '13th Gen Raptor Lake',
    '14th Gen Raptor Lake Refresh',
    'Core Ultra Series 1 (Meteor Lake)',
    'Core Ultra Series 2 (Arrow Lake)',
    'AMD Ryzen 7000 Series',
    'AMD Ryzen 8000 Series',
    'AMD Ryzen 9000 Series',
    'AMD EPYC 9004/9005 Series',
    'Intel Xeon Scalable (Emerald Rapids)',
  ],
  'Processor Cores': [
    'Quad-Core (4 Cores)',
    'Hexa-Core (6 Cores)',
    'Octa-Core (8 Cores)',
    'Deca-Core (10 Cores)',
    'Dodeca-Core (12 Cores)',
    '14 Cores',
    '16 Cores',
    '24 Cores',
    '32 Cores',
    '64 Cores',
    '96 Cores',
    '128 Cores',
  ],
  'Socket Type': [
    'LGA1700',
    'LGA1851',
    'AM4',
    'AM5',
    'LGA4677',
    'SP5',
  ],
  'RAM Capacity': ['8GB', '16GB', '24GB', '32GB', '48GB', '64GB', '96GB', '128GB', '256GB'],
  'RAM Type': [
    'DDR4 3200MHz',
    'DDR4 3600MHz',
    'DDR5 5600MHz',
    'DDR5 6000MHz',
    'DDR5 6400MHz',
    'LPDDR5X',
    'DDR5 ECC Registered',
  ],
  'Storage Capacity': [
    '256GB',
    '512GB',
    '1TB',
    '2TB',
    '4TB',
    '8TB',
    '15.36TB (Enterprise)',
  ],
  'Storage Type': [
    'NVMe PCIe 4.0 SSD',
    'NVMe PCIe 5.0 SSD',
    'SATA III 2.5" SSD',
    'Enterprise SAS 12G HDD',
    'Enterprise U.2 / U.3 NVMe',
  ],
  'Graphics Memory': [
    'Integrated',
    'Integrated / Shared',
    '6GB GDDR6',
    '8GB GDDR6',
    '12GB GDDR6X',
    '16GB GDDR6X',
    '24GB GDDR6X',
    '48GB GDDR6 (Enterprise)',
  ],
  'Form Factor': [
    'ATX',
    'Micro-ATX',
    'Mini-ITX',
    'E-ATX',
    '1U Rackmount',
    '2U Rackmount',
    '4U Rackmount',
  ],
  'Display Technology': ['LED Backlit', 'IPS Anti-Glare', 'OLED (True Black)', 'Mini-LED', 'Retina Display', 'TN Panel'],
  Touchscreen: ['No', 'Yes (Multi-Touch)', 'Yes (Stylus Active Pen)'],
  Color: ['Silver', 'Space Gray', 'Black', 'Dark Ash Silver', 'Platinum', 'Midnight Blue', 'White'],
  'Backlit Keyboard': ['Yes', 'No', 'RGB Per-Key Backlit'],
  'Keyboard Type': ['Island-style Chiclet', 'Full-size with Numpad', 'Compact Tenkeyless', 'Mechanical Switches', 'Low-profile'],
  'Fingerprint Reader': ['Yes', 'No'],
  'Stylus / Pen Support': ['No', 'Yes (Included)', 'Yes (Supported, Sold Separately)'],
  'Included Bag / Case': ['No', 'Yes (Executive Laptop Bag)', 'Yes (Protective Sleeve)'],
  'Power Source & Battery': ['Rechargeable 3-Cell 45Wh', 'Rechargeable 3-Cell 56Wh', 'Rechargeable 4-Cell 70Wh', 'Rechargeable 6-Cell 90Wh', 'AC Power Supply 65W USB-C', 'AC Power Supply 100W USB-C', 'AC Power Supply 230W Smart Barrel'],
  'Computer Form Factor': ['Notebook / Clamshell', '2-in-1 Convertible (360°)', 'Ultraportable / Thin & Light', 'Mobile Workstation', 'Ruggedized Field Laptop'],
  'Computer Intended Use': ['Home & Business', 'Enterprise Corporate Fleet', 'Pro Creator & CAD', 'High-Performance Gaming', 'Engineering & Data Science'],
  'Keyboard Language': [
    'English (US)',
    'English / Arabic (Bilingual GCC)',
    'English / Russian',
    'English / French',
  ],
  'Operating System': [
    'No OS / FreeDOS',
    'DOS',
    'Windows 11 Pro',
    'Windows 11 Home',
    'Windows Server 2022',
    'Red Hat Enterprise Linux',
    'Ubuntu Server LTS',
  ],
  // Enterprise Storage / HDD presets
  'HDD RPM': ['5400 RPM', '7200 RPM', '10000 RPM', '15000 RPM'],
  'HDD Cache': ['64MB Cache', '128MB Cache', '256MB Cache', '512MB Cache'],
  'HDD Interface Protocol': ['SATA III 6Gb/s', 'SAS 12Gb/s', 'PCIe Gen4 U.2 / U.3', 'Fibre Channel (FC)'],
  'HDD Intended Workload': ['Enterprise 24/7 Datacenter', 'NAS (Network Attached Storage)', 'Surveillance / CCTV Continuous Recording', 'Desktop / Workstation Client'],
  'HDD Series': ['Seagate IronWolf Pro', 'Seagate Exos Enterprise', 'Western Digital Red Pro', 'Western Digital Gold Enterprise', 'Western Digital Ultrastar', 'Toshiba MG Series Enterprise'],
  'HDD Form Factor': ['3.5" Large Form Factor (LFF)', '2.5" Small Form Factor (SFF)', 'M.2 2280 NVMe', 'U.2 2.5" NVMe'],
  Warranty: [
    '3 Years Official Manufacturer Warranty',
    '2 Years Regional GCC Warranty',
    '1 Year Official Warranty',
    'One Year Shop Warranty',
    '3 Months Reseller Replacement Warranty',
    'Lifetime Limited Warranty (RAM/SSD)',
  ],
  'Country of Origin': [
    'Taiwan',
    'United States',
    'Japan',
    'South Korea',
    'Germany',
    'China',
    'Malaysia',
    'Vietnam',
  ],
};

export interface SpecGroupDefinition {
  id: string;
  name: string;
  description: string;
  fields: {
    key: string;
    label: string;
    placeholder: string;
    presetKey?: string;
    type: 'select' | 'text' | 'number';
  }[];
}

export const SPECIFICATION_GROUPS: SpecGroupDefinition[] = [
  {
    id: 'core',
    name: 'Platform & Architecture',
    description: 'Hardware generation, condition, processor socket, cores, and categorization',
    fields: [
      { key: 'Condition', label: 'Condition', placeholder: 'Select hardware condition', presetKey: 'Condition', type: 'select' },
      { key: 'Product Category', label: 'Hardware Category', placeholder: 'Select product taxonomy', presetKey: 'Product Category', type: 'select' },
      { key: 'Processor Brand', label: 'Processor Brand', placeholder: 'Intel / AMD / etc.', presetKey: 'Processor Brand', type: 'select' },
      { key: 'Processor Generation', label: 'Processor Architecture', placeholder: 'e.g. 14th Gen Raptor Lake', presetKey: 'Processor Generation', type: 'select' },
      { key: 'Processor Model', label: 'Processor Model', placeholder: 'e.g. Core i9-14900K, Ryzen 9 7950X', type: 'text' },
      { key: 'Processor Cores', label: 'Processor Core Configuration', placeholder: 'e.g. Dodeca-Core (12 Cores)', presetKey: 'Processor Cores', type: 'select' },
      { key: 'Socket Type', label: 'Socket Architecture', placeholder: 'e.g. LGA1700, AM5', presetKey: 'Socket Type', type: 'select' },
    ],
  },
  {
    id: 'memory_storage',
    name: 'Memory & High-Speed Storage',
    description: 'RAM frequency, channel capacity, SSD bus protocols, and HDD capacity',
    fields: [
      { key: 'RAM Capacity', label: 'RAM Capacity', placeholder: 'e.g. 32GB, 64GB', presetKey: 'RAM Capacity', type: 'select' },
      { key: 'RAM Type', label: 'RAM Specification', placeholder: 'e.g. DDR5 6000MHz', presetKey: 'RAM Type', type: 'select' },
      { key: 'Storage Capacity', label: 'Storage Capacity', placeholder: 'e.g. 1TB, 2TB', presetKey: 'Storage Capacity', type: 'select' },
      { key: 'Storage Type', label: 'Storage Interface', placeholder: 'e.g. NVMe PCIe 5.0 SSD', presetKey: 'Storage Type', type: 'select' },
    ],
  },
  {
    id: 'graphics_power',
    name: 'Graphics, Chassis & Power Delivery',
    description: 'Discrete GPU chipset, VRAM buffer, power consumption, and chassis footprint',
    fields: [
      { key: 'Graphics Card', label: 'Graphics Accelerator', placeholder: 'e.g. NVIDIA RTX 4090 24GB', type: 'text' },
      { key: 'Graphics Memory', label: 'VRAM Pool', placeholder: 'e.g. 24GB GDDR6X', presetKey: 'Graphics Memory', type: 'select' },
      { key: 'Form Factor', label: 'Chassis / Board Form Factor', placeholder: 'e.g. ATX, 2U Rackmount', presetKey: 'Form Factor', type: 'select' },
      { key: 'Power Supply Wattage', label: 'PSU / TDP Rating', placeholder: 'e.g. 125W, 850W Titanium', type: 'text' },
    ],
  },
  {
    id: 'laptop_mobile',
    name: 'Laptop & Mobile Computing',
    description: 'Dedicated specifications for notebooks, ultrabooks, and mobile workstations',
    fields: [
      { key: 'Computer Form Factor', label: 'Laptop Form Factor', placeholder: 'e.g. Notebook / Clamshell', presetKey: 'Computer Form Factor', type: 'select' },
      { key: 'Computer Intended Use', label: 'Intended Specialization', placeholder: 'e.g. Home & Business Laptop', presetKey: 'Computer Intended Use', type: 'select' },
      { key: 'Color', label: 'Chassis Color', placeholder: 'e.g. Silver, Space Gray', presetKey: 'Color', type: 'select' },
      { key: 'Display Technology', label: 'Display Panel Technology', placeholder: 'e.g. LED Backlit, IPS', presetKey: 'Display Technology', type: 'select' },
      { key: 'Touchscreen', label: 'Touchscreen Capability', placeholder: 'No / Yes', presetKey: 'Touchscreen', type: 'select' },
      { key: 'Keyboard Type', label: 'Keyboard Architecture', placeholder: 'e.g. Island-style Chiclet', presetKey: 'Keyboard Type', type: 'select' },
      { key: 'Backlit Keyboard', label: 'Keyboard Backlighting', placeholder: 'Yes / No', presetKey: 'Backlit Keyboard', type: 'select' },
      { key: 'Fingerprint Reader', label: 'Biometric Security', placeholder: 'Yes / No', presetKey: 'Fingerprint Reader', type: 'select' },
      { key: 'Stylus / Pen Support', label: 'Stylus / Pen Digitizer', placeholder: 'Yes / No', presetKey: 'Stylus / Pen Support', type: 'select' },
      { key: 'Included Bag / Case', label: 'Included Protective Bag/Case', placeholder: 'Yes / No', presetKey: 'Included Bag / Case', type: 'select' },
      { key: 'Power Source & Battery', label: 'Battery & Charger', placeholder: 'e.g. Rechargeable 3-Cell 56Wh', presetKey: 'Power Source & Battery', type: 'select' },
      { key: 'Disclosures', label: 'Commercial Disclosures', placeholder: 'e.g. Factory sealed official MENA batch', type: 'text' },
    ],
  },
  {
    id: 'enterprise_storage',
    name: 'Enterprise HDD & Server Storage',
    description: 'Specialized enterprise spindle metrics, cache buffers, and enterprise protocols',
    fields: [
      { key: 'HDD Series', label: 'Drive Family / Series', placeholder: 'e.g. Seagate Exos, WD Red Pro', presetKey: 'HDD Series', type: 'select' },
      { key: 'HDD RPM', label: 'Spindle Speed (RPM)', placeholder: 'e.g. 7200 RPM, 10000 RPM', presetKey: 'HDD RPM', type: 'select' },
      { key: 'HDD Cache', label: 'Buffer Cache Size', placeholder: 'e.g. 256MB Cache', presetKey: 'HDD Cache', type: 'select' },
      { key: 'HDD Interface Protocol', label: 'Host Interface Protocol', placeholder: 'e.g. SATA III 6Gb/s, SAS 12G', presetKey: 'HDD Interface Protocol', type: 'select' },
      { key: 'HDD Form Factor', label: 'Drive Form Factor', placeholder: 'e.g. 3.5" Large Form Factor', presetKey: 'HDD Form Factor', type: 'select' },
      { key: 'HDD Intended Workload', label: 'Workload Rating', placeholder: 'e.g. Enterprise 24/7 Datacenter', presetKey: 'HDD Intended Workload', type: 'select' },
    ],
  },
  {
    id: 'display_system',
    name: 'Display, OS & Regional Compliance',
    description: 'Display metrics, factory operating system, warranty terms, and origin',
    fields: [
      { key: 'Screen Size', label: 'Display Diagonal', placeholder: 'e.g. 16.1", 27" 4K', type: 'text' },
      { key: 'Resolution', label: 'Native Resolution', placeholder: 'e.g. 1920x1080 FHD, 4K UHD', type: 'text' },
      { key: 'Operating System', label: 'Factory OS', placeholder: 'e.g. Windows 11 Pro, DOS, Ubuntu', presetKey: 'Operating System', type: 'select' },
      { key: 'Keyboard Language', label: 'Keyboard Layout', placeholder: 'e.g. English / Arabic (GCC)', presetKey: 'Keyboard Language', type: 'select' },
      { key: 'Warranty', label: 'Warranty Coverage', placeholder: 'Select official warranty tier', presetKey: 'Warranty', type: 'select' },
      { key: 'Country of Origin', label: 'Country of Origin', placeholder: 'Select manufacturing origin', presetKey: 'Country of Origin', type: 'select' },
      { key: 'Part Number', label: 'Manufacturer Part No. (MPN)', placeholder: 'e.g. A38BGET#BH5', type: 'text' },
      { key: 'Model', label: 'Hardware Model Number', placeholder: 'e.g. ProBook 460 G11', type: 'text' },
    ],
  },
];
